# Generated by Django 3.2.4 on 2024-07-21 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
