# Generated by Django 3.2.4 on 2024-07-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flan',
            name='flan_uuid',
        ),
        migrations.AddField(
            model_name='flan',
            name='category',
            field=models.CharField(choices=[('tradicional', 'Tradicional'), ('innovador', 'Innovador'), ('sin_azucar', 'Sin Azúcar')], default='tradicional', max_length=50),
        ),
        migrations.AddField(
            model_name='flan',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flan',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='flan',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
